// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvygDrMi_jL93HeTrkH7dW3b6pCUEBnLw',
    appId: '1:678366592316:web:20e3ea206dd42110bd7239',
    messagingSenderId: '678366592316',
    projectId: 'ditonton-10cf7',
    authDomain: 'ditonton-10cf7.firebaseapp.com',
    storageBucket: 'ditonton-10cf7.appspot.com',
    measurementId: 'G-1P7R3GLE74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQakhyZFLSrX7_8HOd4_6e4Beg_ukDVw',
    appId: '1:678366592316:android:08abee3b2118c908bd7239',
    messagingSenderId: '678366592316',
    projectId: 'ditonton-10cf7',
    storageBucket: 'ditonton-10cf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByZADKLM-VyEi64OZtxJMtPNKbQDQ8KC0',
    appId: '1:678366592316:ios:a4c6bb6bc7ffb00cbd7239',
    messagingSenderId: '678366592316',
    projectId: 'ditonton-10cf7',
    storageBucket: 'ditonton-10cf7.appspot.com',
    iosClientId: '678366592316-devnqehovk6q5lph4m1omtqemlvgsat5.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
